@ignore
@node Glossary
@chapter Glossary
@c This 'ignore' section fools texinfo-all-menus-update into creating
@c proper menus for this chapter.
@end ignore

@keyword{BNF}

@keyword{bovinate}

@keyword{bovine lambda}

@keyword{LALR}

@keyword{lexer}

@keyword{lexical tokens}
The output of the lexer as well as the input to the parser.

@keyword{LL}

@keyword{overloadable}
Some functions are defined via @code{define-overload}.
These can be overloaded via ....

@keyword{parser}
A program that converts @ref{lexical tokens} to
@ref{semantic tokens}.

@keyword{semantic tokens}

@keyword{wisent parser}

@keyword{}
