@ignore
@node Glossary
@chapter Glossary
@c This 'ignore' section fools texinfo-all-menus-update into creating
@c proper menus for this chapter.
@end ignore

@keyword{BNF}

@keyword{bovinate}

@keyword{bovine lambda}

@keyword{context}

@keyword{LALR}

@keyword{lexer}

@keyword{LL}

@keyword{nonterminal}

@keyword{overloadable}
Some functions are defined via @code{define-overload}.
These can be overloaded via ....

@keyword{parser}
A program that converts @b{tokens} to @b{tags}.

@keyword{tag}

@keyword{tokens}
The output of the lexer as well as the input to the parser.

@keyword{wisent parser}
